### ISSUE TITLE
Support multi-object files

### ISSUE THREAD

**Issue by tkellogg** [hgrsd/drivel#1]
It currently panics when you give it a file with one object per line, like

```
{"user_id": null, "user_email": null, "user_name": null, "email_domain": null, "org": null, "method": "POST", "path": "/logged_in", "status_code": 200, "latency": 0.09175515174865723, "timestamp": "2023-09-05T21:38:34+0000", "response_len": 450, "properties": {}}
{"user_id": 2, "user_email": "tim@fr.ai", "user_name": "Tim", "email_domain": "fr.ai", "org": null, "method": "GET", "path": "/datasets/web", "status_code": 200, "latency": 0.0032494068145751953, "timestamp": "2023-09-05T21:38:35+0000", "response_len": 672, "properties": {}}
{"user_id": 2, "user_email": "tim@fr.ai", "user_name": "Tim", "email_domain": "fr.ai", "org": null, "method": "GET", "path": "/datasets/file", "status_code": 200, "latency": 0.3335745334625244, "timestamp": "2023-09-05T21:38:35+0000", "response_len": 85195, "properties": {}}
{"user_id": null, "user_email": null, "user_name": null, "email_domain": null, "org": null, "method": "POST", "path": "/logged_in", "status_code": 200, "latency": 0.04735732078552246, "timestamp": "2023-09-05T22:13:40+0000", "response_len": 459, "properties": {}}
{"user_id": 3, "user_email": "justin@fr.ai", "user_name": "Justin", "email_domain": "fr.ai", "org": null, "method": "GET", "path": "/datasets/web", "status_code": 200, "latency": 0.002116680145263672, "timestamp": "2023-09-05T22:13:42+0000", "response_len": 672, "properties": {}}
```

An easy way to handle this might be to ignore everything after the first complete object, e.g. this works fine:

```
❯ cat usage_log.json | head -n1 | drivel describe
```

But realistically, I'd want it treated as if the top level is an implicit array

**Comment by hgrsd** [comment]
My initial thoughts were that turning invalid JSON into valid JSON should be a concern handled somewhere outside `drivel`, for example with `sed` in the pipeline:

```sh
cat usage_log.json | sed '1s/^/[/;$!s/$/,/;$s/$/]/' | drivel describe
```
 
But then I came across https://jsonlines.org/ which seems to describe a format with a spec that your input data adheres to. And that format is pretty close to "normal" JSON. 

So now I'm wondering whether the solution here would be to add a `--jsonl` flag. If that flag is set by the caller then under the hood we can wrap the input in square brackets and add commas after each (but the last line) before feeding it to serde and the inference engine. WDYT?

If that sounds reasonable then I think it's a good idea to get #2 implemented first.

**Comment by tkellogg** [comment]
For reference, `jq` will handle either rather transparently. The jsonlines format is used a lot for data (i.e. not configuration). Like with logs, you can just append a line to the file without rewriting the whole file. Also, Spark mostly works with the lines format.

The main trouble with handling it transparently is that you need support from your JSON parser. A lot of them will choke on the second object.

Another way to think about it — jsonlines vs json **is part of** the schema we're trying to introspect. e.g. when I fed that file into `drivel describe`, I hadn't opened the file in months and didn't actually know the format. I expected drivel to tell me what the format is.

**Comment by hgrsd** [comment]
So you're saying it's useful too for a user to be _told_ that the file is in JSON lines vs regular JSON.

That makes me think that we shouldn't be messing with string manipulation to pretend the input data is normal JSON before feeding it to the inference engine (and producing data from it).

I'm thinking that in addition to `infer_schema` which takes a single &serde::Value, we could add an `infer_schema_from_iter` that takes an iterator over `&serde::Value`. That way we can do something like this as a fallback (if parsing as a single JSON structure fails):

```rust
// in main.rs
let values = stdin.lines().map(|line| serde_json::from_str(&line);
let inferred_schema = drivel::infer_schema_from_iter(values); // after this line all the processing would be the same

// in infer.rs:
pub fn infer_schema_from_iter<'a>(values: impl Iterator<Item = &'a serde_json::Value>) -> SchemaState {
    values.map(|v| infer_schema(v)).fold(SchemaState::Initial, merge)
}
```

**Comment by hgrsd** [comment]
Something like https://github.com/hgrsd/drivel/pull/4 - wdyt?

**Comment by tkellogg** [comment]
Yeah, this is great
